/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 18-Feb-2018 10:20:49
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 12
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h 
 */
#define TAPS_LP15_FIR 12
const float32_t baLP15Fir[TAPS_LP15_FIR] = { 0.002900700790033, 0.01178069945337, 0.04136489221709, 0.09430976798124,
        0.1545795505518, 0.1950643890064, 0.1950643890064, 0.1545795505518, 0.09430976798124, 0.04136489221709,
        0.01178069945337, 0.002900700790033 };
