/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 05-Jan-2018 23:26:45
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II Transposed, Second-Order Sections
 * Number of Sections  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h 
 */
#include "arm_math.h"
#define SECTIONS_ELIPNOTCH60 7*2 //7 Sectors for filter coeffs and 7 more for input gains
const float32_t baElipticNotch60Coeffs[SECTIONS_ELIPNOTCH60 * (5)] =
        {
                0.6538685428701, 0, 0,
                0, 0,

                1, -1.986720925655, 1,
                1.985924506031, -0.9995327524727,

                0.6538685428701, 0, 0,
                0, 0,

                1, -1.987727680948, 1,
                1.987591744901, -0.9995616870033,

                0.9990331690468, 0, 0,
                0, 0,

                1, -1.986808845914, 1,
                1.984305540096, -0.9980106683987,

                0.9990331690468, 0, 0,
                0, 0,

                1, -1.987645865832, 1,
                1.986280473081, -0.9981483167363,

                0.9966616579513, 0, 0,
                0, 0,

                1, -1.986988444813, 1,
                1.979180537743, -0.9930588514759,

                0.9966616579513, 0, 0,
                0, 0,

                1, -1.987475312829, 1,
                1.981969689788, -0.9936338881474,

                2.317435152036, 0, 0,
                0, 0,

                1, -1.987234192229, 1,
                1.969870853028, -0.9825251203209
        };

