/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 06-Jan-2018 11:59:16
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II Transposed, Second-Order Sections
 * Number of Sections  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h 
 */
#include "arm_math.h"
#define SECTIONS_ELIPNOTCH120 7*2 //7 Sectors for filter coeffs and 7 more for input gains
const float32_t baElipticNotch120Coeffs[SECTIONS_ELIPNOTCH120 * (5)] =
        {
                0.8239841513951, 0, 0,
                0, 0,

                1, -1.948213350683, 1,
                1.946903221361, -0.9993410171921,

                0.8239841513951, 0, 0,
                0, 0,

                1, -1.949887968001, 1,
                1.949902526605, -0.9993597746685,

                0.9987393761447, 0, 0,
                0, 0,

                1, -1.948365019746, 1,
                1.944982018286, -0.9974505032923,

                0.9987393761447, 0, 0,
                0, 0,

                1, -1.949740715399, 1,
                1.948190493509, -0.9975267437949,

                0.9967201567745, 0, 0,
                0, 0,

                1, -1.948662235513, 1,
                1.94108978603, -0.9933569260272,

                0.9967201567745, 0, 0,
                0, 0,

                1, -1.94944966347, 1,
                1.944217476459, -0.9935438003305,

                1.463771815906, 0, 0,
                0, 0,

                1, -1.94905745127, 1,
                1.938300860912, -0.9889622644508

        };
